name: CI/CD

env:
  CI: true

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '*.md'
jobs:
  ci-cd:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: NPM CI
        run: npm ci

      - name: Repository build
        run: npm run build

      - name: Tests (with coverage)
        run: npm test -- --coverage

      - name: Build website (Github pages)
        run: npm run build-doc --if-present

      - name: Publish website on GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.2
        with:
          build_dir: dist-ghpages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          parallel: true

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  coverage-end:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls End
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          parallel-finished: true
